# Generated by Django 3.0.2 on 2020-12-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translater', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
